# Generated by Django 5.0.3 on 2024-04-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('class1', models.CharField(max_length=50)),
                ('image', models.ImageField(default='a', upload_to='static/images')),
                ('ar', models.CharField(choices=[('a', 'a'), ('b', 'b')], default='a', max_length=50)),
                ('text', models.TextField(default='a')),
                ('boole', models.BooleanField(default=True)),
                ('url1', models.URLField(default='https://www.abc.com')),
            ],
        ),
        migrations.CreateModel(
            name='signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(default='a', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='toppers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(default='a', upload_to='statics/images')),
                ('text', models.CharField(default='text', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='abc',
            name='image',
            field=models.ImageField(default='a', upload_to='statics/images'),
        ),
        migrations.AlterField(
            model_name='abc',
            name='name',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
