# Generated by Django 5.0.3 on 2024-04-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_courses_signin_toppers_abc_image_alter_abc_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='courses',
        ),
    ]
