# Generated by Django 5.0.3 on 2024-04-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='cour_ses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image2', models.ImageField(default='a', upload_to='statics/images')),
                ('name2', models.CharField(default='a', max_length=50)),
            ],
        ),
    ]
