# Generated by Django 5.0.3 on 2024-04-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cour_ses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50)),
                ('email1', models.CharField(max_length=50)),
                ('message', models.CharField(default='a', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image2', models.ImageField(default='a', upload_to='statics/images')),
                ('name2', models.CharField(default='text', max_length=200)),
                ('back_name', models.CharField(default='text', max_length=200)),
                ('text2', models.CharField(default='text', max_length=200)),
                ('text3', models.CharField(default='text', max_length=200)),
                ('text4', models.CharField(default='text', max_length=200)),
                ('text5', models.CharField(default='text', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='courses1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image12', models.ImageField(default='a', upload_to='statics/images')),
                ('name12', models.CharField(default='text', max_length=200)),
                ('back_name1', models.CharField(default='text', max_length=200)),
                ('text12', models.CharField(default='text', max_length=200)),
                ('text13', models.CharField(default='text', max_length=200)),
                ('text14', models.CharField(default='text', max_length=200)),
                ('text15', models.CharField(default='text', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='courses2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image121', models.ImageField(default='a', upload_to='statics/images')),
                ('name121', models.CharField(default='text', max_length=200)),
                ('back_name11', models.CharField(default='text', max_length=200)),
                ('text121', models.CharField(default='text', max_length=200)),
                ('text131', models.CharField(default='text', max_length=200)),
                ('text141', models.CharField(default='text', max_length=200)),
                ('text151', models.CharField(default='text', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='cour_ses',
        ),
    ]
