# Generated by Django 5.0.3 on 2024-04-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contact_courses_courses1_courses2_delete_cour_ses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='courses1',
            name='description1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='courses2',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
