# Generated by Django 5.0.3 on 2024-04-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_courses_description_courses1_description1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='syllabus',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='courses1',
            name='syllabus',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='courses2',
            name='syllabus',
            field=models.TextField(default=''),
        ),
    ]
