# Generated by Django 5.0.3 on 2024-04-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_courses_syllabus_courses1_syllabus_courses2_syllabus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses1',
            old_name='syllabus',
            new_name='descriptionn1',
        ),
        migrations.RenameField(
            model_name='courses2',
            old_name='syllabus',
            new_name='descriptionn11',
        ),
        migrations.AddField(
            model_name='courses',
            name='descriptionn',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='courses',
            name='text6',
            field=models.CharField(default='text', max_length=200),
        ),
        migrations.AddField(
            model_name='courses1',
            name='syllabus1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='courses1',
            name='text16',
            field=models.CharField(default='text', max_length=200),
        ),
        migrations.AddField(
            model_name='courses2',
            name='syllabus2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='courses2',
            name='text161',
            field=models.CharField(default='text', max_length=200),
        ),
    ]
