# Generated by Django 5.0.3 on 2024-04-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_syllabus_courses1_descriptionn1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='descriptionnn',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='courses',
            name='text7',
            field=models.CharField(default='text', max_length=200),
        ),
        migrations.AddField(
            model_name='courses1',
            name='descriptionn2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='courses1',
            name='text26',
            field=models.CharField(default='text', max_length=200),
        ),
        migrations.AddField(
            model_name='courses2',
            name='descriptionn12',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='courses2',
            name='text61',
            field=models.CharField(default='text', max_length=200),
        ),
    ]
