# Generated by Django 5.0.3 on 2024-04-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_courses_descriptionnn_courses_text7_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses2',
            old_name='description',
            new_name='description2',
        ),
    ]
