# Generated by Django 5.0.3 on 2024-05-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_description_courses2_description2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teach_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(default='a', upload_to='statics/images')),
                ('heading', models.CharField(max_length=50)),
                ('para', models.TextField(default='text')),
            ],
        ),
        migrations.RenameField(
            model_name='courses2',
            old_name='description2',
            new_name='description',
        ),
    ]
