# Generated by Django 5.0.3 on 2024-05-06 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signin',
        ),
    ]
