# Generated by Django 5.0.3 on 2024-05-06 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_signin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
