# Generated by Django 5.0.3 on 2024-05-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='index_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img2', models.ImageField(default='a', upload_to='statics/images')),
                ('heading1', models.CharField(max_length=50)),
                ('para1', models.TextField(default='text')),
            ],
        ),
    ]
