# Generated by Django 5.0.3 on 2024-05-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_index_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageh', models.ImageField(default='a', upload_to='statics/images')),
                ('nameh', models.CharField(default='text', max_length=200)),
                ('back_nameh', models.CharField(default='text', max_length=200)),
                ('texth', models.CharField(default='text', max_length=200)),
                ('texth1', models.CharField(default='text', max_length=200)),
                ('texth2', models.CharField(default='text', max_length=200)),
                ('texth3', models.CharField(default='text', max_length=200)),
                ('descriptionh', models.TextField(default='')),
                ('texth4', models.CharField(default='text', max_length=200)),
                ('descriptionh1', models.TextField(default='')),
                ('texth5', models.CharField(default='text', max_length=200)),
                ('descriptionh2', models.TextField(default='')),
                ('syllabush', models.TextField(default='')),
            ],
        ),
    ]
