# Generated by Django 5.0.3 on 2024-05-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_home_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='abc',
            name='descriptionh',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='abc',
            name='descriptionh1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='abc',
            name='descriptionh2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='abc',
            name='price',
            field=models.CharField(default='Rs.25000', max_length=20),
        ),
        migrations.AddField(
            model_name='abc',
            name='syllabush',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='abc',
            name='texth3',
            field=models.CharField(default='text', max_length=200),
        ),
        migrations.AddField(
            model_name='abc',
            name='texth4',
            field=models.CharField(default='text', max_length=200),
        ),
        migrations.AddField(
            model_name='abc',
            name='texth5',
            field=models.CharField(default='text', max_length=200),
        ),
    ]
